/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "awsamplifysagemaker-20200507233052-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d1eceaccj7729a.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "smInferenceClient",
            "endpoint": "https://pyrjeyncah.execute-api.ap-southeast-2.amazonaws.com/dev",
            "region": "ap-southeast-2"
        }
    ]
};


export default awsmobile;
