/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "awsamplifysagemaker-20200509193038-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d36dnxwsj991l3.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "smInferenceClient",
            "endpoint": "https://zyy9dccxyj.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
